alias k kubectl
alias kaf 'k apply -f'
alias kccc 'k config current-context'
alias kcdc 'k config delete-context'
alias kcsc 'k config set-context'
alias kcuc 'k config use-context'
alias kdd 'k describe deployment'
alias kdeld 'k delete deployment'
alias kdeli 'k delete ingress'
alias kdelp 'k delete pods'
alias kdels 'k delete svc'
alias kdelsec 'k delete secret'
alias kdi 'k describe ingress'
alias kdp 'k describe pods'
alias kds 'k describe svc'
alias kdsec 'k describe secret'
alias ked 'k edit deployment'
alias kei 'k edit ingress'
alias kep 'k edit pods'
alias kes 'k edit svc'
alias keti 'k exec -ti'
alias kgd 'k get deployment'
alias kgi 'k get ingress'
alias kgp 'k get pods'
alias kgrs 'k get rs'
alias kgs 'k get svc'
alias kgsec 'k get secret'
alias kl 'k logs'
alias klf 'k logs -f'
alias krh 'k rollout history'
alias krsd 'k rollout status deployment'
alias kru 'k rollout undo'
alias ksd 'k scale deployment'
